---
format_version: 10
common:
  deploy-task: &deploy-tasks
    - exec:
        command: bash
        arguments:
          - -c
          - echo "Deployment on ${ENV_NAME} environment triggered... "

pipelines:
  node-microservice:
    group: microservices
    materials:
      mainGit:
        git: https://github.com/mtararujs/ci_course
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - echo "Building node application"
      - deploy-dev:
          environment_variables:
            ENV_NAME: DEV
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-dev:
          jobs:
            test:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - echo "Running tests on DEV environment"
      - deploy-int:
          environment_variables:
            ENV_NAME: INT
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-int:
          jobs:
            test:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - echo "Running tests on INT environment"
      - deploy-prd:
          environment_variables:
            ENV_NAME: PRD
          jobs:
            deploy:
              tasks: *deploy-tasks
      - test-prd:
          jobs:
            test:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - echo "Running tests on PRD environment"
